### ISSUE TITLE
KeyError when checking for prefix in admin.py

### ISSUE THREAD

**Issue by skewerr** [skewerr/deskbot#3]
The `settings.ini` file doesn't contain predetermined prefixes, so without setting them, should a user different than the admin try to use `.enable` or `.disable`, a KeyError will be raised and the bot will crash. The file should be generated with preset values first, if it doesn't exist, and should probably be checked for needed properties.

**Comment by 6AA4FD** [comment]
can't you just define an initial value in vars.py before you source the ini?

**Comment by skewerr** [comment]
It will be a preset value, but since I'm going to extend the use of settings.ini, other properties are going to be made. Given some other options are to be implemented, including services(atheme, anope, etc.) and maybe other stuff, I believe it's worthwhile to make a module to generate the initial settings.ini file.

**Comment by skewerr** [comment]
Fixed with the implementation of `settings.py`
