### ISSUE TITLE
Doesn't support different services than anope.

### ISSUE THREAD

**Issue by skewerr** [skewerr/deskbot#4]
NickServ authentication check through services like atheme doesn't work for those services work differently. NickServ authentication by the bot is currently "obligatory" and should be done if and only if a password is given on startup.

Support for other services should be implemented and messed with by flags used on startup.

**Comment by mikotohe2** [comment]
Update on this, Atheme uses ACC, which produces the same output as STATUS in anope. 
From the atheme wiki:
```
ACC

ACC returns parsable information about a user's login status. Note that on many networks, /whois shows similar information faster and more reliably. The answer is in the form <nick> ACC <digit>:
0 - account or user does not exist
1 - account exists but user is not logged in
2 - user is not logged in but recognized (see ACCESS)
3 - user is logged in

If the account is omitted the user's nick is used. Account * means the account the user is logged in with.

Syntax: ACC
Syntax: ACC <nick>
Syntax: ACC <nick> <account>
Syntax: ACC <nick> *

Example:
/msg NickServ ACC jilles *
```

**Comment by skewerr** [comment]
Thanks a bunch for this, @mikotohe2. The bot supports atheme and anope. Other services will have to be worked on as needed.
