### ISSUE TITLE
The bot should know when to try identifying with NickServ.

### ISSUE THREAD

**Issue by skewerr** [skewerr/deskbot#6]
Despite supporting anope, some networks have a thing with identifying at the wrong point in time. SystemNet has this issue, making the use of `.ident` necessary. Rizon doesn't have problems with this, though now and then it will fail to identify with Rizon's services and `.ident` is issued.

**Comment by skewerr** [comment]
I'll look into the messages it receives from the server to be able to tell when to identify with NickServ.

**Comment by mikotohe2** [comment]
That should be easy enough, right? Just monitor for the first message from NickServ, and send the identify command after that? Since once NickServ has sent a message, it's pretty much guaranteed to accept the identify command.

**Comment by skewerr** [comment]
You're right, @mikotohe2. Thanks for the suggestion, it was implemented and WOOOO!
